---
# - name: create random dir
#   shell: mktemp -d
#   register: tmp_dir

# - name: clone down homeroom deploy script
#   git: 
#     repo: https://github.com/afouladi7/quay-workshop.git
#     dest: "{{ tmp_dir.stdout }}"

# - name: deploy homeroom
#   shell: "/usr/bin/sh {{ tmp_dir.stdout }}/.workshop/workshop-scripts/deploy-spawner.sh"
#   ignore_errors: true


- name: Deploy the homeroom spawner
  shell: |
    oc process -f \
    https://raw.githubusercontent.com/RedHatGov/workshop-spawner/develop/templates/hosted-workshop-production.json \
    -p SPAWNER_NAMESPACE=homeroom \
    -p CLUSTER_SUBDOMAIN=$CLUSTER_SUBDOMAIN \
    -p WORKSHOP_NAME=service-mesh-workshop \
    -p CONSOLE_IMAGE=quay.io/openshift/origin-console:4.5 \
    -p WORKSHOP_IMAGE=quay.io/redhatgov/service-mesh-workshop-dashboard:latest \
    -p CUSTOM_TAB_1=Quay=https://quay.$CLUSTER_SUBDOMAIN | oc apply -n homeroom -f -


## End Homeroom


# Leave this as the last task in the playbook.
# --------------------------------------------
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool