---
- name: create random dir
  shell: mktemp -d
  register: tmp_dir

- name: clone down homeroom deploy script
  git: 
    repo: https://github.com/afouladi7/quay-workshop.git
    dest: "{{ tmp_dir.stdout }}"

- name: deploy homeroom
  shell: "/usr/bin/sh {{ tmp_dir.stdout }}/.workshop/workshop-scripts/deploy-spawner.sh"
  ignore_errors: true

## End Homeroom

# Leave this as the last task in the playbook.
# --------------------------------------------
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool