---
- name: Get router sub domain
  shell: oc get route -n openshift-console --output=json | grep -m 1 routerCanonicalHostname | awk '{ print $2 }' | sed -r 's/[\",]//g'
  register: CLUSTER_SUBDOMAIN_RETURN

- name: Store the cluster hostname
  set_fact:
    CLUSTER_HOSTNAME: "{{ CLUSTER_SUBDOMAIN_RETURN.stdout | regex_replace('apps','') }}"

- name: Store the subdomain
  set_fact:
    CLUSTER_SUBDOMAIN: "{{ CLUSTER_SUBDOMAIN_RETURN.stdout }}"

- name: Create the quay ns and install the operator
  shell: |
    oc apply -f https://raw.githubusercontent.com/afouladi7/quay-workshop/master/templates/quay.yml
  ignore_errors: true

- name: Deploy the homeroom spawner
  shell: |
      oc process -f https://raw.githubusercontent.com/afouladi7/quay-workshop/master/templates/hosted-workshop-production.json \
          -p SPAWNER_NAMESPACE=homeroom \
          -p CLUSTER_SUBDOMAIN={{ CLUSTER_SUBDOMAIN }} \
          -p WORKSHOP_NAME=quay-workshop \
          -p CONSOLE_IMAGE=quay.io/openshift/origin-console:4.7 \
          -p WORKSHOP_IMAGE=quay.io/redhatgov/quay-workshop:latest \
          -p CUSTOM_TAB_1=Quay=https://quayecosystem-quay-quay.{{ CLUSTER_SUBDOMAIN }} | oc apply -n homeroom -f -



## TODO's
# - Resolve the one user per cluster piece with RHPDS using the GUID manager
# - Ensure clusters are using smallest cluster footprint size available in rhpds catalog
# - Cleanup and finish lab content guide
#   - Lab navigation is referencing absolute github links
#   - Explain the groupings box in the developer console (tags)
#   - Remove first page (instructor notes)
#   - Add steps to monitor the rollout of quay object
# - Remove secret created by install-script / rebuild image after
# - Quay route in the console is not happy


# Leave this as the last task in the playbook.
# --------------------------------------------
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool